### ISSUE TITLE
Use system stylesheet instead of Arc colored sidebar

### ISSUE THREAD

**Issue by aspirus-in** [blackhole89/notekit#106]
The sidebar is Arc colored, use the system stylesheet instead

**Comment by blackhole89** [comment]
You're probably right that I should stop hardcoding the Arc-style colouring (originally added in because I got annoyed that Arc had hardcoded the "black semi-transparent" look to only apply to the sidebars of certain apps like Nautilus), but I need to find some approach to set it apart visually from the text editing field.

In the meantime, a possible workaround you can do on your end is to delete the sidebar-related entries from stylesheet.css (usually in data/ or /usr/share/notekit/data/).
