### ISSUE TITLE
CMakeLists.txt

### ISSUE THREAD

**Issue by anthrolisp** [blackhole89/notekit#15]
When I try to run cmake . within the folder, I get the following error:

```
CMake Error: The source directory "/home/justin/Downloads/notekit-20190911" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

I'm running Ubuntu.

**Comment by blackhole89** [comment]
Did you clone the git repository, or only download one of the binary builds? The latter do not contain source or makefiles, so you can't `cmake` them. In order to build from source, please follow GIthub's instructions to `git clone` the repository, and make sure you have the development headers mentioned in the README installed.

**Comment by anthrolisp** [comment]
Thanks for the clarification. It worked!
