### ISSUE TITLE
zero byte size files prevent notekit from starting

### ISSUE THREAD

**Issue by hgkamath** [blackhole89/notekit#26]
using portable 64bit exe version notekit-20190911.zip

## steps to reproduce 
started notekit
created 4 files in left side bar
closed notekit, did not enter anything into any of the files
restart notekit
-> notekit does nto start

## workaround
opening an editor like vim and enterring a spacebar into the zero byte files allows starting

**Comment by LyesSaadi** [comment]
Thank you! I was having this issue, and I didn't understand the issue. Your workaround saved me ! Especially that while trying in a wm it worked, which drove me crazy :smile:!

**Comment by blackhole89** [comment]
Ugh. I think I fixed it for now, but the very nature of the bug is bizarre - it seems that (only) when the text buffer is completely empty, a redraw event for the container is emitted for the first time _before_ its size allocation event. I only create a buffer texture for rendering the pen input once I know the viewport size, so this resulted in attempting to work with the buffer texture before it was initialised...

**Comment by LyesSaadi** [comment]
I have updated the copr repo as well.
