### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by mhalano** [blackhole89/notekit#28]
Would be nice to have this software packaged as a Ubuntu Snap. Snaps are very portable between distros so more people could use it.

**Comment by blackhole89** [comment]
cf. #24; unfortunately, in both cases my impression from briefly assessing how much work it would be came out as "more than I have the time for at the moment". I would be very happy if someone volunteered to create one, though!

**Comment by fbruetting** [comment]
I would recommend Flatpaks, as these are decentral and work on vastly more distributions than snaps. Furthermore, I’m sure that new package formats would in fact save you time, as you would be able to distribute your application in a uniform way. This is absolutely important. For you as the maintainer, the most important advantage, is that with the current approach, you will receive bug reports which you cannot reproduce, mainly because every system has another permutation of libraries installed. With these new package formats, it would be exactly the same for everyone, no matter if he/she runs Arch, Debian, Fedora, RHEL or Gentoo.

**Comment by blackhole89** [comment]
Well, for what it's worth, I tried creating an AppImage today (after stumbling upon appimage-builder, which promised to make it easy). The bottom line was that after spending some three hours trying to squash bugs in the tooling that ranged from it refusing GLIBC 2.30 position-independent executables because they register as a different binary format to it being unable to find the correct folder for Gtk's dynamically-loaded pixbuf loader modules, I finally got a running image but (1) it could not access any of the system fonts and (2) it had no write permissions anywhere, including the home folder (so you couldn't save notes). Neither of the two issues proved particularly amenable to googled solutions. At this stage, I think I'll stick with a policy that if anyone creates a working appimage/snap/flatpak/$yourfavouritepackagemanagerreplacement, I will happily host it, but unless there is some dramatic improvement to the stability, usability and documentation of at least one existing solution, I will not spend any more time on it myself.
