### ISSUE TITLE
UX improvement: draw and  text in different planes

### ISSUE THREAD

**Issue by gcoimbra** [blackhole89/notekit#48]
Many times I have misplaced drawings and it messed up the text or the drawing. I had to do the
drawing again.
I think it would be more useful to have to planes, one for the drawing and other for the text.
So each won't interfere in each other.
Another nice thing about this is that I can place text inside drawings, which currently is very hard.

**Comment by blackhole89** [comment]
I've had plans to add this for the longest time, but haven't gotten around to implement this. The problem with a separate drawing layer is that if the underlying text moves (e.g. because you added some lines at the top of the document), all drawings will wind up in the wrong place - for instance, if you circled a word on the overlay, the circle will now be on top of something else.

To counteract this, I was thinking of letting "overlay" drawings still be anchored at a canonical point in text (say, the center of each connected family of strokes). This, however, will require quite a bit of testing to get it to behave like a user expects. I generally prefer to not add a feature at all, rather than adding it in a broken/frustrating form...

**Comment by Torkin1** [comment]
I'm answering here since I'm interested in this feature too. Id' like to give my two cents on this.
- You could register each time a newline, space or tab character is entered in the text layer at some line, and move all drawings accordingly in the drawing layer. For istance, if a newLine character is inserted in the n-th line, all drawings from the n+1-th line and below will be moved by a certain amount of pixels, mapped to the newLine character.
- You could implement the possibility to add text in the drawing layer itself.

I Hope these ideas will be useful. Thank you for your work, i really enjoy using NoteKit!

**Comment by blackhole89** [comment]
Thanks for the feedback!

I don't think it's quite as simple, unfortunately.

* There are lots of different ways that the flow of a document could change, not just adding/removing newlines, spaces and tabs - for example, the height of a line may change due to formatting (as #-headings are bigger), resizing the window may cause word-wrap, and markdown and LaTeX rendering could hide or reveal parts of the text. Even the system font and DPI settings could change. Anchors seem more robust to all of these.

* Text in the drawing layer would make us depart from "vanilla markdown with a small set of necessary extras" quite significantly, and anyhow does not seem to cover the standard usecase of drawing over text: you first write some text, then decide that you want to mark it up with a highlighter or similar.

**Comment by Torkin1** [comment]
@blackhole89 I don't think that highlight text with drawing would be the main use case for combining text with drawings, as users can use markdown tags for the same purpose. Instead, a user could use text to add descriptions to the drawings, or to assign names to vectors and axes ...
Anyway I understand that there are other priorities first, I hope that this discussion will be useful in the future.
