### ISSUE TITLE
[Feature request] Hide files sidebar

### ISSUE THREAD

**Issue by gcoimbra** [blackhole89/notekit#55]
Hi. I think it will be nice if there's an option to hide the tree view of notes (sidebar).

A lot of space will be gained when using notekit half screen.

BTW, nice app. It's unique!

**Comment by blackhole89** [comment]
Thanks!

I can probably add this, but between the following three options, which one do you think is better?

* The sidebar collapses to a maybe 16px wide, but full-height clickable button, say containing a ▶. This would save most of the space occupied by it, but not all. When the sidebar is expanded, there is a big button containing a ◀ occupying the entire bottom row of the sidebar.

* A small button, containing a ◀ or ▶ depending on sidebar state, is perpetually displayed in the bottom left corner, on top of everything else. There is a small chance that this button will occlude a part of the sidebar in an annoying way.

* There's a menu option (perhaps in the application menu that does nothing right now) for "show/hide sidebar". This is the least intrusive option (and most cautious re: cluttering up the UI), but requires two clicks rather than one to show/hide it, and is less discoverable. (You can still switch between notes with ctrl+tab and ctrl+shift+tab even when the sidebar is hidden.)

Thanks!

**Comment by blackhole89** [comment]
(I've implemented the last option for the time being in the latest commit, because it was fast enough to do... let let me know if I should reopen this if you're more interested in the other two.)

**Comment by gcoimbra** [comment]
@blackhole89 Thanks a lot. That was a nice move. But I didn't found the menu option to hide the sidebar. Well it seems that there's no menu at all
