### ISSUE TITLE
WM_CLASS is set incorrectly

### ISSUE THREAD

**Issue by sp1ritCS** [blackhole89/notekit#69]
NoteKit is not using the correct application icon under Wayland.

i manually tried to refresh icon cache, desktop db & gdk pixbuf query db.

Also the name is now just the name of the binary.

![grafik](https://user-images.githubusercontent.com/31540351/99996910-521e1b00-2db4-11eb-8ba4-ddb42ec13d11.png)

![grafik](https://user-images.githubusercontent.com/31540351/99996943-5cd8b000-2db4-11eb-8456-894ddbde393e.png)

This has obviously something to do with the change from `notekit` to `com.github.blackhole89.notekit` for desktop and icon files

**Comment by sp1ritCS** [comment]
I've done some more testing, and it is not only broken on wayland.

On X11, the application name is "Notekit" (I have no idea from where it gets this name. the only refrence of "Notekit" in the code is sourceview/notekit.xml ➡ style-schema _name="Notekit") and the Application Icon is the accessories-text-editor that gets set during initialization https://github.com/blackhole89/notekit/blob/af313fbd3710ce6e2f0f51e770099b91de3d8ad7/mainwindow.cpp#L73 (AFAIK on Wayland it is not possible to change the application icon this way, so it is ignored)

In both environments, the wm_class is incorrectly set, yet they are different. On Wayland it is just the name of the binary ("notekit") and on X11 it is, as written above "Notekit". It should be set to "com.github.blackhole89.notekit".
If I launch notekit like this `./_build/notekit --class com.github.blackhole89.notekit`, the name and icon is correctly set ("NoteKit" as specified in the .desktop file) on X11. On Wayland it does not work.

The other thing, that works on both environments is renaming the binary to com.github.blackhole89.notekit, because this is the same on both and the [gnome shell window tracker](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/src/shell-window-tracker.c) can use it.

**Comment by blackhole89** [comment]
So what's the intended way of doing this? Gtkmm's documentation [claims](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Window.html#ac6a7119c34bcfc31fdc27a8061a6f8f1) that set_wmclass is deprecated, but doesn't suggest any replacement. The only context in which I currently pass one of those dbus/java style "reversed domain" strings is the parameter to Gtk::Application::create (which is currently "test.notekit" and should probably be changed to "com.github.blackhole89.notekit" since that's what y'all have decided it should be... :P).

So what's the official way to set a window's icon in Wayland? Everything I can find on the matter by cursory googling suggests you need to have a .desktop file named after the binary, which seems supremely awkward (isn't Linux supposed to not have the sort of strong coupling between running processes and FS entries that they have in Windows land?).

**Comment by sp1ritCS** [comment]
well, other applications are able to have a desktop icon with different name of binary. (e.g. gnome software)

I'm unsure if wm_class is deprecated on wayland, but gnome lookingglass still lists it. As written above, the gnome shell window tracker does a bit more than just binary name and wm_class. It also checks the gtk_application_id from gio.

If you are using gnome, you could use gnome lg and test how you can change either _nkwindow_`.get_gtk_application_id()` or _nkwindow_`.wm_class`

**Comment by blackhole89** [comment]
Yeah, the main window was being created before the application was associated with it. I changed that, which resulted in the wmclass not changing, but a bunch of new identifiers extracted by `xprop`:

```
_GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/com/github/blackhole89/notekit/window/1"
_GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/com/github/blackhole89/notekit"
_GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.7061"
_GTK_APPLICATION_ID(UTF8_STRING) = "com.github.blackhole89.notekit"
```

Can you see if this is sufficient, or we have to set_wmclass after all?

**Comment by sp1ritCS** [comment]
Yes, this works and is probably this intended way of doing it.

Closing this.

**Comment by sp1ritCS** [comment]
Consider removing https://github.com/blackhole89/notekit/blob/177bbdd1787ac1a8a5fd3b379d62ba209db49808/mainwindow.cpp#L73 that notekit gets the correct icon on X aswell.
