### ISSUE TITLE
Build with MSVC?

### ISSUE THREAD

**Issue by PikachuHy** [blackhole89/notekit#94]
Can the notekit be compiled with MSVC?

**Comment by sp1ritCS** [comment]
> Can the notekit be compiled with MSVC?

If you manage to set msvc up that it links against gtkmm3, gtksourceviewmm3, fontconfig and jsoncpp you might be able to. However you'll need GNU coreutils (or a drop in replacement), as NoteKit uses a few `system()` calls to do stuff with files (the ones you'd need are mv, mkdir, touch & rm; if you have rustc installed you can use uutils as it's easier to build on windows. See the .github/actions/windows.yml on how to, as we are building them for your mingw releases too).

I think the issue is fontconfig, as it not of any use on windows. But I think the only place where NoteKit uses uses fontconfig is
https://github.com/blackhole89/notekit/blob/47ab43fd00fe129a914338e404360a1bc69b5281/mainwindow.cpp#L45
on Windows you shoud be able to replace it with [AddFontResourceExA](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-addfontresourceexa) to add the Charter fonts that are located in data/fonts/.

Before attempting to build on msvc take a look at the windows.patch (and maybe the Apple/llvm.patch) as some things are broken on non-gcc or non-posix os's.
